server:
  port: 9090

#  dubbo.scan.basePackages=com.alibaba.edas.boot
#  dubbo.application.name=dubbo-provider-demo
#  dubbo.registry.address=nacos://127.0.0.1:8848
dubbo:
  scan:
    base-packages: com.alibaba.edas.boot
  application:
    name: transaction
  registry:
    address: nacos://127.0.0.1:8848

spring:
  application:
    name: transaction
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public