server:
  port: 7070

spring:
  application:
    name: center-bff

dubbo:
  # 注册中心地址
  registry:
    address: nacos://127.0.0.1:8848
    register: false

rocketmq:
  name-server: "127.0.0.1:9876"
  producer:
    group: payment-create-group