server:
  port: 4040

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment-center
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  # 注册中心地址
  registry:
    address: nacos://127.0.0.1:8848
  provider:
    filter: paymentProvider

rocketmq:
  name-server: "127.0.0.1:9876"
